<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>AMIS.WebApi.Migrations.PostgreSQL</RootNamespace>
    <AssemblyName>AMIS.WebApi.Migrations.PostgreSQL</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Procurement\**" />
    <EmbeddedResource Remove="Procurement\**" />
    <None Remove="Procurement\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\framework\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\..\modules\Inventories\Inventories.Infrastructure\Inventories.Infrastructure.csproj" />
    <ProjectReference Include="..\..\modules\Todo\Todo.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Inventories\" />
    <Folder Include="Identity\" />
    <Folder Include="Tenant\" />
    <Folder Include="Todo\" />
  </ItemGroup>
</Project>
